#!/usr/bin/env python3
"""
Train Audio-Visual models (binary + multiclass) using ONLY audio + image features.
These models are used when sensor CSV data is unavailable (e.g. test data).

Reads from cached features (generated by cache_features.py).
Training takes ~30 seconds since features are pre-computed.

Output:
  artifacts/binary_model_av.joblib      (audio-visual binary)
  artifacts/multiclass_model_av.joblib  (audio-visual multiclass)
  artifacts/binary_av_metrics.json
  artifacts/multiclass_av_metrics.json
"""

import os
import sys
import json
import time
import logging
import numpy as np
import joblib
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import (
    f1_score, precision_score, recall_score, roc_auc_score,
    classification_report, confusion_matrix
)
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

ARTIFACTS_DIR = "artifacts"
CACHE_PATH = os.path.join(ARTIFACTS_DIR, "feature_cache.npz")


def load_av_features():
    """Load cached features, return audio+image concatenated (no sensor)."""
    if not os.path.exists(CACHE_PATH):
        logging.error(f"Feature cache not found: {CACHE_PATH}")
        logging.error("Run: python cache_features.py first")
        sys.exit(1)
    
    cache = np.load(CACHE_PATH, allow_pickle=True)
    
    # Audio (120) + Image (97) = 217 features — DROP sensor
    X_train = np.concatenate([cache["train_audio"], cache["train_image"]], axis=1)
    X_val = np.concatenate([cache["val_audio"], cache["val_image"]], axis=1)
    
    y_train_binary = cache["train_labels"]
    y_val_binary = cache["val_labels"]
    
    train_codes = cache["train_label_codes"]
    val_codes = cache["val_label_codes"]
    
    logging.info(f"Loaded AV features: train={X_train.shape}, val={X_val.shape}")
    logging.info(f"Train class balance: good={np.sum(y_train_binary==0)}, defect={np.sum(y_train_binary==1)}")
    
    return X_train, X_val, y_train_binary, y_val_binary, train_codes, val_codes


def train_binary_av(X_train, X_val, y_train, y_val):
    """Train binary defect detector using audio+image features."""
    logging.info("\n=== Training Binary AV Model ===")
    
    # Class weight for imbalance
    n_good = np.sum(y_train == 0)
    n_defect = np.sum(y_train == 1)
    scale = n_good / max(n_defect, 1)
    
    param_dist = {
        "n_estimators": [200, 300, 500],
        "max_depth": [4, 6, 8],
        "learning_rate": [0.05, 0.1, 0.15],
        "subsample": [0.7, 0.8, 0.9],
        "colsample_bytree": [0.7, 0.8, 0.9],
        "min_child_weight": [1, 3, 5],
        "reg_alpha": [0, 0.1, 0.5],
        "reg_lambda": [1, 2, 5],
    }
    
    base = XGBClassifier(
        scale_pos_weight=scale,
        eval_metric="logloss",
        use_label_encoder=False,
        random_state=42,
        tree_method="hist",
    )
    
    search = RandomizedSearchCV(
        base, param_dist, n_iter=30, cv=3,
        scoring="f1", random_state=42, n_jobs=-1, verbose=0
    )
    
    t0 = time.time()
    search.fit(X_train, y_train)
    logging.info(f"  Binary search done in {time.time()-t0:.1f}s")
    logging.info(f"  Best params: {search.best_params_}")
    
    model = search.best_estimator_
    
    # Evaluate
    y_prob = model.predict_proba(X_val)[:, 1]
    
    # Find best threshold
    best_f1 = 0
    best_thresh = 0.5
    for t in np.arange(0.1, 0.9, 0.01):
        preds = (y_prob >= t).astype(int)
        f = f1_score(y_val, preds)
        if f > best_f1:
            best_f1 = f
            best_thresh = t
    
    y_pred = (y_prob >= best_thresh).astype(int)
    
    metrics = {
        "f1": float(f1_score(y_val, y_pred)),
        "precision": float(precision_score(y_val, y_pred)),
        "recall": float(recall_score(y_val, y_pred)),
        "roc_auc": float(roc_auc_score(y_val, y_prob)),
        "best_threshold": float(best_thresh),
        "features_used": "audio(120) + image(97) = 217",
    }
    
    logging.info(f"  Binary AV — F1: {metrics['f1']:.4f}, AUC: {metrics['roc_auc']:.4f}, Threshold: {best_thresh:.3f}")
    
    # Save
    joblib.dump(model, os.path.join(ARTIFACTS_DIR, "binary_model_av.joblib"))
    with open(os.path.join(ARTIFACTS_DIR, "binary_av_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    
    return model, best_thresh, metrics


def train_multiclass_av(X_train, X_val, train_codes, val_codes):
    """Train multiclass defect type classifier using audio+image features."""
    logging.info("\n=== Training Multiclass AV Model ===")
    
    # Only defective samples for type classification
    train_defect = train_codes != "00"
    val_defect = val_codes != "00"
    
    X_train_d = X_train[train_defect]
    X_val_d = X_val[val_defect]
    codes_train = train_codes[train_defect]
    codes_val = val_codes[val_defect]
    
    le = LabelEncoder()
    y_train_d = le.fit_transform(codes_train)
    y_val_d = le.transform(codes_val)
    
    n_classes = len(le.classes_)
    logging.info(f"  Classes: {list(le.classes_)} ({n_classes} types)")
    logging.info(f"  Train defects: {len(X_train_d)}, Val defects: {len(X_val_d)}")
    
    param_dist = {
        "n_estimators": [200, 300, 500],
        "max_depth": [4, 6, 8],
        "learning_rate": [0.05, 0.1, 0.15],
        "subsample": [0.7, 0.8, 0.9],
        "colsample_bytree": [0.7, 0.8, 0.9],
        "min_child_weight": [1, 3, 5],
    }
    
    base = XGBClassifier(
        objective="multi:softprob",
        num_class=n_classes,
        eval_metric="mlogloss",
        use_label_encoder=False,
        random_state=42,
        tree_method="hist",
    )
    
    search = RandomizedSearchCV(
        base, param_dist, n_iter=30, cv=3,
        scoring="f1_macro", random_state=42, n_jobs=-1, verbose=0
    )
    
    t0 = time.time()
    search.fit(X_train_d, y_train_d)
    logging.info(f"  Multiclass search done in {time.time()-t0:.1f}s")
    
    model = search.best_estimator_
    
    # Evaluate
    y_pred = model.predict(X_val_d)
    
    macro_f1 = float(f1_score(y_val_d, y_pred, average="macro"))
    weighted_f1 = float(f1_score(y_val_d, y_pred, average="weighted"))
    
    # Per-class report
    report = classification_report(y_val_d, y_pred, target_names=le.classes_, output_dict=True)
    
    logging.info(f"  Multiclass AV — Macro F1: {macro_f1:.4f}, Weighted F1: {weighted_f1:.4f}")
    logging.info(f"\n{classification_report(y_val_d, y_pred, target_names=le.classes_)}")
    
    metrics = {
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
        "per_class": {cls: {"f1": report[cls]["f1-score"], "precision": report[cls]["precision"], "recall": report[cls]["recall"]}
                      for cls in le.classes_},
        "features_used": "audio(120) + image(97) = 217",
    }
    
    # Save
    joblib.dump(model, os.path.join(ARTIFACTS_DIR, "multiclass_model_av.joblib"))
    joblib.dump(le, os.path.join(ARTIFACTS_DIR, "label_encoder_av.joblib"))
    with open(os.path.join(ARTIFACTS_DIR, "multiclass_av_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    
    return model, le, metrics


def main():
    logging.info("=" * 60)
    logging.info("  Audio-Visual Model Training (No Sensor Data)")
    logging.info("=" * 60)
    
    X_train, X_val, y_train_bin, y_val_bin, train_codes, val_codes = load_av_features()
    
    # Train binary
    bin_model, threshold, bin_metrics = train_binary_av(X_train, X_val, y_train_bin, y_val_bin)
    
    # Train multiclass
    multi_model, le, multi_metrics = train_multiclass_av(X_train, X_val, train_codes, val_codes)
    
    # Pipeline score
    binary_f1 = bin_metrics["f1"]
    type_macro_f1 = multi_metrics["macro_f1"]
    final_score = 0.6 * binary_f1 + 0.4 * type_macro_f1
    
    logging.info("\n" + "=" * 60)
    logging.info(f"  AUDIO-VISUAL MODEL RESULTS")
    logging.info(f"  Binary F1:       {binary_f1:.4f}")
    logging.info(f"  Type Macro F1:   {type_macro_f1:.4f}")
    logging.info(f"  Final Score:     {final_score:.4f} ({final_score*100:.1f}%)")
    logging.info("=" * 60)
    
    # Save pipeline metrics
    with open(os.path.join(ARTIFACTS_DIR, "pipeline_av_metrics.json"), "w") as f:
        json.dump({
            "binary_f1": binary_f1,
            "type_macro_f1": type_macro_f1,
            "final_score": final_score,
            "best_threshold": threshold,
            "features": "audio(120) + image(97) = 217 dims",
            "note": "Trained without sensor features for test data that lacks CSVs",
        }, f, indent=2)


if __name__ == "__main__":
    main()
